"""Update category model

Revision ID: 1d6bc5b31bf2
Revises: 6190c43f4011
Create Date: 2026-09-24 11:33:32.392800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d6bc5b31bf2'
down_revision: Union[str, Sequence[str], None] = '6190c43f4011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('image_url', sa.String(length=200), nullable=True))
    op.add_column('categories', sa.Column('slug', sa.String(length=100), nullable=True))

    op.execute("""
        UPDATE categories
        SET slug = LOWER(REPLACE(name, ' ', '-'))
        WHERE slug IS NULL
    """)

    op.alter_column(
        'categories',
        'slug',
        existing_type=sa.String(length=100),
        nullable=False
    )

    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_column('categories', 'slug')
    op.drop_column('categories', 'image_url')
    # ### end Alembic commands ###
