upstream fastapi_ecommerce {
    server web:8000;
}

server {
    listen 80;

    server_name pystore.ru;

    # FastAPI API
    location /api/ {
        proxy_pass http://fastapi_ecommerce;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    # Swagger UI
    location /docs {
        proxy_pass http://fastapi_ecommerce;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    # OpenAPI schema for Swagger
    location /openapi.json {
        proxy_pass http://fastapi_ecommerce;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    # Uploaded media
    location /media/ {
        alias /var/www/media/;
    }

    # React frontend
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}